### PR TITLE
BLD: Be consistent with __glibc exports

### PR DESCRIPTION
**Pull request by carterbox**
Unguard __glib exports so that packages build on all archs have minimum glibc constraints.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

During a recent but hunt with libcufile and pytorch, we discovered that the libcufile aarch64 packages did not have a minimum __glibc constraint because they were still built with the 2.17 sysroot.

Discussing in the last core meeting, the uninterested consensus was that non-x86 sysroots should have consistent run_exports on __glibc.

Closes https://github.com/conda-forge/cuda-feedstock/issues/56

### CODE REVIEW

**Comment by carterbox** [comment]
@conda-forge-admin, please rerender

**Comment by carterbox** [comment]
Maybe I'm wrong, but I feel like when building the sysroot package, the sysroot of the contain must match? i.e. we cannot use alma9 to build sysroot=2.17?

**Comment by carterbox** [comment]
Or we're getting all the stuff from RPM unpacked by conda, so it doesn't matter? Lemme know and I can adjust conda-forge.yml as needed.

**Comment by h-vetinari** [comment]
> Or we're getting all the stuff from RPM unpacked by conda, so it doesn't matter?

Exactly, it's coming from the downloaded RPMs, not from the image.

**Comment by isuruf** [comment]
When adding these constraints, we decided to not add `__glibc` for the baseline. i.e. `__glibc>=2.12` was not added to `linux-64` and `__glibc>=2.17` was not added to `linux-aarch64` and `__osx>=10.9` was not added to `osx-64`.
So, this is consistent in that sense.

**Comment by jakirkham** [comment]
Think some of the history here is the virtual packages were a new concept in Conda 4.7.0. The macOS and Linux virtual packages were later added in Conda 4.8.0. Lastly the UNIX and Windows virtual packages were added in Conda 4.9.0

So at the time we decided to not add virtual packages to existing packages to avoid causing issues on old versions of Conda

Though that feature has now been available for over 5 years. So it seems worthwhile to revisit whether we add these to packages

Refs:
* https://github.com/conda/conda/pull/8267
* https://github.com/conda/conda/pull/9358
* https://github.com/conda/conda/pull/9349
* https://github.com/conda/conda/pull/10214

**Pull request closed without merging**
