### PR TITLE
WIP make a 2.12.2 CDT

### PR DESCRIPTION
**Pull request by beckermr**
This PR extracts the 2.12.2 sysroot from our latest build of the ctng compilers.

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by isuruf** [comment]
I'd rather we patch the header needed for `aligned_alloc`.

**Comment by beckermr** [comment]
But we don't know if that is the only change needed to match the ABI and API, right? 

This way we do not have to guess.

**Comment by isuruf** [comment]
We are doing the same thing for 2.17 on aarch64 and ppc64le, so I don't see a reason not to.

**Comment by beckermr** [comment]
> We are doing the same thing for 2.17 on aarch64 and ppc64le, so I don't see a reason not to.

Where?

**Comment by isuruf** [comment]
ct-ng builds 2.17 on aarch64 and ppc64le and we are going to replace that with the 2.17 glibc from CDT right?

**Comment by beckermr** [comment]
Yes but where are the patches we are using with 2.17 now?

**Comment by isuruf** [comment]
Those are in `ct-ng`.
gibc 2.12 x86_64 patches = 2.17 aarch64 + aligned_alloc patch.

**Comment by beckermr** [comment]
Ahhhh. They are in the anaconda fork. 

https://github.com/ContinuumIO/crosstool-ng/tree/master/packages/glibc/2.12.2

**Comment by beckermr** [comment]
I had assumed (wrongly and without much basis) that aligned alloc was in 2.17.

hmmmmmm

**Comment by beckermr** [comment]
Well, given that it worked with the 2.17 CDT, I guess that is true actually.

**Comment by beckermr** [comment]
OK. I am still catching up here. 

 ## Option 1

We apply the aligned alloc patch to 2.12 centos headers. We don't actually know if this will generate a sysroot that is the same as the 2.12.2 one we use now, but we suspect it might. We'd have to inspect the source code to see if it has the rest of the patches that form 2.12.2.


## Option 2

We extract the 2.12.2 CDT from the gcc_impl_linux-64 package we have now. (This PR.) This procedure is inelegant and hard to reproduce. It does, however, guarantee exact compatibility. 

Did I get this right?

**Comment by isuruf** [comment]
Yes

**Comment by beckermr** [comment]
There is also the issue of the 2.17 patches from ctng (https://github.com/ContinuumIO/crosstool-ng/tree/master/packages/glibc/2.17) we have been using relative to 2.17 from centos 7.

Uggggh.

**Comment by isuruf** [comment]
Most of those patches were ported from RHEL7/CentOS7, so that's fine.

**Comment by beckermr** [comment]
My taxonomy Of Linux dists is really bad. The fedora patches too?

I guess my feeling is that we should be doing the minimal thing here. So that to me would mean only using the  centos 2.17 CDT for Linux-64 and hacking out the sysroot from ctng for the rest of the platforms. 

However my experience in these issues is non-existent. Thus generally I’ll defer to you here. 

One test we might consider is using some of the tools from the ABI lab to figure out what we might be missing in terms of headers and symbols etc. this doesn’t cover bugs however.

**Comment by beckermr** [comment]
Actually no. Let’s patch the header and move on. The code built against these cdts is used on tons of other machines without issues. 

Where do we want the patches? Probably in a 2.12 branch here?

**Comment by isuruf** [comment]
> Where do we want the patches? Probably in a 2.12 branch here?

Sure. Or add a new variant in `recipe/conda_build_config.yaml` whichever is easier for you.

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Pull request closed without merging**
