### PR TITLE
ENH fix sysroot location and add shell CDT for 2.12

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [ ] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
ok @isuruf I think this one is ready to go!

**Comment by beckermr** [comment]
We good to merge this one @isuruf?

**Comment by isuruf** [comment]
Can you add a variant for the previous way so that we can use that when building the compilers

**Comment by beckermr** [comment]
> Can you add a variant for the previous way so that we can use that when building the compilers

Why do we need this? The symlink takes care of that.

**Comment by isuruf** [comment]
We need to have `conda_cos7` name in `sysroot=2.17` and we need the compilers to be independent of the `conda_cos*`

**Comment by beckermr** [comment]
Yup. I made a PR for the cos7 packages too.

**Comment by beckermr** [comment]
Wait, are you saying the compiler build will pick up on the sysroot name even with the symlink?

**Comment by isuruf** [comment]
> Wait, are you saying the compiler build will pick up on the conda_cos6 sysroot name even with the symlink?

Yes

**Comment by beckermr** [comment]
🤦

**Comment by isuruf** [comment]
conda-build will only know about files in `x86_64-conda-linux-gnu` as being in  `x86_64-conda_cos6-linux-gnu`. That's how soft links work.

**Comment by beckermr** [comment]
But conda build remakes the links on install and we point the compilers their. I guess this has to do with other things like linking etc?

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
ok @isuruf - How's this?

**Comment by isuruf** [comment]
Looks good to me. Thanks

**Pull request merged**
