### PR TITLE
fix: remove current repodata hacks for cos7

### PR DESCRIPTION
**Pull request by beckermr**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This PR removes current repodata hacks for cos7.

### CODE REVIEW

**Comment by beckermr** [comment]
@conda-forge-admin rerender

**Comment by beckermr** [comment]
@conda-forge/linux-sysroot this one is ready for review!

**Comment by h-vetinari** [comment]
Wasn't the conclusion from the last time we discussed this in the core call that bioconda isn't ready for the removal of the sysroot hacks?

CC @mbargull

**Comment by beckermr** [comment]
No, the sysroot hacks only effect if the packages get pulled into current_repodata.json. They do not effect track_features or similar.

**Comment by beckermr** [comment]
This PR leaves the track features in place for now. Also, I thought we had concluded that we'd keep the track features?

**Comment by h-vetinari** [comment]
> Also, I thought we had concluded that we'd keep the track features?

My understanding was that this was for the foreseeable future, at least until bioconda has rolled out `{{ stdlib("c") }}`, but not necessarily indefinitely.

> No, the current repodata hacks only affect if the packages get pulled into current_repodata.json. They do not affect track_features or similar.

OK, the distinction between those things wasn't 100% clear to me.

**Pull request merged**
