### PR TITLE
Glibc 2.34 from alma 9

### PR DESCRIPTION
**Pull request by h-vetinari**
~Builds on #79 and predecessors, so review those first.~

### CODE REVIEW

**Comment by h-vetinari** [comment]
This is the output of the `update.py`, 
```
(builder) E:\conda-forge\linux-sysroot-feedstock\recipe>python update.py
WARNING:root:Could not download rpm for glibc-headers from https://repo.almalinux.org/vault/9.3/AppStream/aarch64/os/Packages/glibc-headers-2.34-83.el9_3.12.aarch64.rpm!
WARNING:root:Could not download rpm for glibc-headers from https://repo.almalinux.org/vault/9.3/AppStream/ppc64le/os/Packages/glibc-headers-2.34-83.el9_3.12.ppc64le.rpm!
```
i.e. exactly two packages aren't available in the expected location w.r.t. x86_64. I've checked the other subfolders on the vault, and indeed the `glibc-headers` seem to be missing completely for 9.3 on aarch/ppc, and this also matches the [info](https://pkgs.org/search/?q=glibc-headers) on pkgs.org. No idea why that's the case. Interestingly it's fine for s390x.

**Review by beckermr — CHANGES_REQUESTED** [review]
Did you move the current main to an alma8 branch?

**Comment by h-vetinari** [comment]
> Did you move the current main to an alma8 branch?

It'll be easy to create a new `v2.28` branch off the latest commit on main (https://github.com/conda-forge/linux-sysroot-feedstock/commit/4bead3616bda93c7bebab2175431552e148f8ce9), irrespective of whether that's before/after merging this. I can do it if you'd like, but Isuru doesn't like non-maintainers doing branch ops, so I'm holding off.

**Comment by beckermr** [comment]
I went ahead and made a v2.28 branch. I will sync it with main if any other PRs get made there before this is merged.

**Review by beckermr — CHANGES_REQUESTED** [review]
We need to add one extra feature to the build to weigh it down relative to v2.28.

**Review by beckermr — APPROVED** [review]
LGTM!

**Review by isuruf — CHANGES_REQUESTED** [review]
What happened to `libnss_nis.so`?
Also I see `aarch64-conda-linux-gnu/sysroot/usr/lib64/libnss_hesiod.so is a symlink with no target`

**Comment by h-vetinari** [comment]
> What happened to `libnss_nis.so`?

See the commit message for https://github.com/conda-forge/linux-sysroot-feedstock/pull/80/commits/6d8749da1b6ec1d0d470fa7d81c7ada3e729c3f3. I couldn't find anything related to that anymore (see also [here](https://pkgs.org/search/?q=nis)).

> Also I see `aarch64-conda-linux-gnu/sysroot/usr/lib64/libnss_hesiod.so is a symlink with no target`

Looks like we need [`nss_hesiod`](https://pkgs.org/search/?q=hesiod) instead...

**Comment by h-vetinari** [comment]
OK, the "symlink with no target" warnings are all gone now. While I don't know what determines the separation between `lib64` and `usr/lib64`, `libnss_hesiod.so` is now next to the other nss libraries:
```
                                              [...]
?rwxrwxr-x 0/0     904648 2024-10-24 22:45:50 x86_64-conda-linux-gnu/sysroot/lib64/libm.so.6 
?rwxrwxr-x 0/0     176840 2024-10-24 22:45:50 x86_64-conda-linux-gnu/sysroot/lib64/libmvec.so.1 
?rwxrwxr-x 0/0      45552 2024-10-24 22:45:50 x86_64-conda-linux-gnu/sysroot/lib64/libnss_compat.so.2 
?rwxrwxr-x 0/0      40872 2024-10-24 22:45:51 x86_64-conda-linux-gnu/sysroot/lib64/libnss_db.so.2 
?rwxrwxr-x 0/0      15344 2024-10-24 22:45:50 x86_64-conda-linux-gnu/sysroot/lib64/libnss_dns.so.2 
?rwxrwxr-x 0/0      15336 2024-10-24 22:45:50 x86_64-conda-linux-gnu/sysroot/lib64/libnss_files.so.2 
?rwxrwxr-x 0/0      28448 2024-10-24 22:45:51 x86_64-conda-linux-gnu/sysroot/lib64/libnss_hesiod.so.2 
?rwxrwxr-x 0/0      15480 2024-10-24 22:45:50 x86_64-conda-linux-gnu/sysroot/lib64/libpthread.so.0
                                              [...]
```

**Comment by isuruf** [comment]
Shall we remove `nss` components from 2.28 and 2.34 both and deal with it when there's a use-case?

**Comment by beckermr** [comment]
That seems fine. I don't even know why we had them in the first place. Is there someone to ask about that?

**Comment by beckermr** [comment]
It appears from #32 that some of the nss stuff was added due to a bug in building the ROS distro packages from work by @wolfv. Maybe he recalls what happened there?

**Comment by h-vetinari** [comment]
> Shall we remove `nss` components from 2.28 and 2.34 both and deal with it when there's a use-case?

Fixed in this PR; opened #83 that backports relevant commits to v2.28

**Comment by isuruf** [comment]
Thanks

**Pull request merged**
